server:
  port: 8900
spring:
  application:
    name: microservice-consumer-movie-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka1:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  