spring:
  application:
    name: microservice-discovery-eureka
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
server:
  port: 8761
eureka:
  instance:
    hostname: eureka1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:admin@eureka1:8761/eureka/
  